`agentos reset` and other minor functionality updates
agentos-project/agentos pull request #137
Opened 2021-09-10 09:52 UTC by nickjalbert

A few small features that helped with debugging as I was finishing the Acme R2D2 port:

* `agentos reset` removes any data backing the agent (e.g. NNs backing a policy, training statistics) so you can re-train from scratch.  `agentos reset -b [backup UUID]` restores the agent backing data specified by the UUID.  I imagine the mechanisms for these might change as you get deeper into your work on hierarchical components and MLFlow.
* Added back in the `--max-iters` flag (renamed to `--max-transitions`) for `agentos run` and `agentos learn`.
* Updated the default environment (the corridor environment you get after `agentos init`) so that it will work with the Acme R2D2 agent.  For example:
```
mkdir corridor_agent
cd corridor_agent
agentos install acme_r2d2_policy
agentos install acme_r2d2_trainer
agentos install acme_r2d2_dataset
agentos run -m 200
```
* The agent prints all its hyperparameters to the console when it runs.

2021-09-11 19:53 UTC, andyk requested changes
Looks good. There is point I'd like to discuss, and possibly change, before we merge (see my comments in the review).

2021-09-11 19:53 UTC, andyk commented on agentos/cli.py
> +def run(num_episodes, agent_file, agentos_dir, max_transitions, verbose):
+1 to supporting a `max_transitions` argument. What do you think of making it optional (i.e. have a default value of `None`)? If it is required, then one can't let an agent just run till its done regardless of how long it takes to achieve that, which seems like an option we want the developer to have.

2021-09-11 19:53 UTC, andyk commented on agentos/core.py
> +    def rollout(self, should_learn, max_transitions):
My comment above bout making `max_transitions` optional would apply here too.

2021-09-11 19:53 UTC, andyk commented on agentos/runtime.py
> +    max_transitions,
Same comment from above about making this optional.

2021-09-12 10:01 UTC, nickjalbert commented
Sounds good, made max_transitions optional everywhere!

2021-09-12 22:09 UTC, andyk approved these changes
LGTM!

2021-09-12 22:09 UTC, merged